
model:
    type: SiameseModel2
    arch: 'resnet50'
    image_size: 256
    input_size: 256
    num_classes: 1108
    num_channels: 3

train:
    batch_size: 32
    max_steps_per_epoch: 15000
    num_epochs: 1000
    # enable_warmup: true
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    batch_size: 8
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-4

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 100
        min_lr: 3e-7
        threshold: 1e-3

loss:
    name: 'cross_entropy'

augmentations:
    affine: 'hard'
    hflip: false
    vflip: true
    rotate90: true
    blur: 0.15
    color: 0.2
    distortion: 0.2
    noise: 0.3
    global_prob: 0.7
#     erase:
#         prob: 0.5
#         min_area: 0.02
#         max_area: 0.4
#         min_ratio: 0.3
#         max_ratio: 3.33
