
model:
    arch: 'resnet18'
    type: 'ClassifierModel'
    image_size: 512
    input_size: 480
    num_classes: 1108
    num_channels: 3
    dropout: 0.5

train:
    path: 'data/train_rgb_512'
    batch_size: 32
    max_steps_per_epoch: 15000
    # enable_warmup: true
    num_epochs: 1000
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    path: 'data/test_rgb_512'
    batch_size: 32
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-4

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 10
        min_lr: 3e-7
        threshold: 1e-3

# cosine:
#     start_lr: 1e-4
#     period: 3
#     period_inc: 1
#     max_period: 5

loss:
    name: 'cross_entropy'

augmentations:
    affine: 'none'
    blur: 0.14758670413953057
    color: 0.1564765286331552
    distortion: 0.7996011390508293
    global_prob: 0.8678675869640207
    hflip: 1
    noise: 0.030820067690145447
    rotate: 1
    rotate90: 0
    vflip: 0
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33

