
model:
    arch: 'resnet18'
    type: 'ClassifierModel'
    image_size: 256
    input_size: 224
    num_classes: 1108
    num_channels: 3
    dropout: 0.5

train:
    path: 'data/train_rgb_256'
    batch_size: 64
    max_steps_per_epoch: 15000
    # enable_warmup: true
    num_epochs: 1000
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    batch_size: 16
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-4

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 100
        min_lr: 3e-7
        threshold: 1e-3

# cosine:
#     start_lr: 1e-4
#     period: 3
#     period_inc: 1
#     max_period: 5

loss:
    name: 'cross_entropy'

augmentations:
    affine: 'medium'
    hflip: true
    vflip: true
    rotate90: true
    # blur: 0.3
    # distortion: 0.2
    # noise: 0.3
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33
