
model:
    arch: 'densenet121'
    type: 'ClassifierModel'
    image_size: 512
    input_size: 512
    num_classes: 1108
    num_channels: 6

train:
    path: 'data/train'
    batch_size: 12
    max_steps_per_epoch: 15000
    # enable_warmup: true
    num_epochs: 1000
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    batch_size: 16
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-3

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 10
        min_lr: 3e-7
        threshold: 1e-3

# cosine:
#     start_lr: 1e-4
#     period: 3
#     period_inc: 1
#     max_period: 5

loss:
    name: 'binary_cross_entropy'
