
general:
    num_folds: 6
    validation_policy: 'split_by_exp'

model:
    arch: 'resnet34'
    type: 'ClassifierModel'
    image_size: 512
    input_size: 480
    num_classes: 1108
    num_channels: 6
    dropout: 0.5

train:
    path: 'data/train'
    batch_size: 32
    max_steps_per_epoch: 15000
    # enable_warmup: true
    num_epochs: 3
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    batch_size: 16
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-3

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 10
        min_lr: 3e-7
        threshold: 1e-3

# cosine:
#     start_lr: 1e-4
#     period: 3
#     period_inc: 1
#     max_period: 5

loss:
    name: 'binary_cross_entropy'

augmentations:
    affine: 'medium'
    hflip: true
    vflip: true
    rotate90: true
    # blur: 0.3
    # distortion: 0.2
    # noise: 0.3
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33

hyperopt:
    enable: true
    max_evals: 50
    augmentations:
        hflip:
            type:   'choice'
            args:   [0, 1]
        vflip:
            type:   'choice'
            args:   [0, 1]
        rotate:
            type:   'choice'
            args:   [0, 1]
        rotate90:
            type:   'choice'
            args:   [0, 1]
        affine:
            type:   'choice'
            args:   ['none', 'soft', 'medium', 'hard']
        noise:
            type:   'uniform'
            args:   [0, 1]
        blur:
            type:   'uniform'
            args:   [0, 1]
        distortion:
            type:   'uniform'
            args:   [0, 1]
        color:
            type:   'uniform'
            args:   [0, 1]
        global_prob:
            type:   'uniform'
            args:   [0.5, 1.0]
