
general:
    num_folds: 6
    validation_policy: 'split_by_exp'

model:
    arch: 'resnet50'
    type: 'ClassifierModel'
    image_size: 512
    input_size: 480
    num_classes: 1108
    num_channels: 6
    dropout: 0.5

train:
    path: 'data/train'
    batch_size: 24
    max_steps_per_epoch: 15000
    # enable_warmup: true
    num_epochs: 1000
    # warmup:
    #     steps: 5000
    #     max_lr: 1e-4
    # mixup:
    #     enable: true
    #     beta_a: 0.3

test:
    batch_size: 16
    # num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 2e-3

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 10
        min_lr: 3e-7
        threshold: 1e-3

loss:
    name: 'binary_cross_entropy'

augmentations:
    affine: 'none'
    blur: 0.8095486475734943
    color: 0.3606188972249108
    distortion: 0.12383837984458157
    global_prob: 0.8714936911097795
    hflip: 1
    noise: 0.6344784294409486
    rotate: 1
    rotate90: 0
    vflip: 0
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33

